<a href="https://colab.research.google.com/github/sharinair14/Basic-ML-Practice/blob/master/GridsearchCV_%26_Random_SearchCV_Example_iris_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

In [73]:
iris=load_iris()

In [74]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [75]:
iris.data[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [76]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [77]:
iris.target[:3]

array([0, 0, 0])

In [78]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [79]:
df=pd.DataFrame(data=iris.data,columns=iris.feature_names)

In [80]:
df['target'] = iris.target

In [81]:
X = df.drop('target',axis=1)

In [82]:
y = df['target']

In [18]:
from sklearn.model_selection import train_test_split

In [83]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [25]:
from sklearn.svm import SVC


**Without Grid Search**

In [23]:
svm = SVC()

In [24]:
svm.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
svm.score(X_test,y_test)

0.9666666666666667

In [27]:
from sklearn.model_selection import cross_val_score

In [29]:
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),X_train,y_train,scoring='accuracy',cv=5)

array([0.95833333, 1.        , 1.        , 1.        , 0.83333333])

In [30]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),X_train,y_train,scoring='accuracy',cv=5)

array([0.91666667, 1.        , 1.        , 1.        , 0.83333333])

In [31]:
cross_val_score(SVC(kernel='linear',C=20,gamma='auto'),X_train,y_train,scoring='accuracy',cv=5)

array([0.95833333, 1.        , 1.        , 1.        , 0.83333333])

**One more mothod without using Grid SearchCV**

In [56]:
kernel=['linear','rbf']
c = [1,10,20,50,100]
scores = {}
for i in kernel:
  for j in c:
    crossval_score = cross_val_score(SVC(kernel=i,C=j,gamma='auto'),X_train,y_train,cv=5,scoring='accuracy')
    scores[i + '_' + str(j)] = np.average(crossval_score)*100
scores

{'linear_1': 95.0,
 'linear_10': 91.66666666666666,
 'linear_100': 91.66666666666666,
 'linear_20': 90.0,
 'linear_50': 90.83333333333334,
 'rbf_1': 95.0,
 'rbf_10': 91.66666666666666,
 'rbf_100': 90.0,
 'rbf_20': 90.0,
 'rbf_50': 90.83333333333334}

**Using Grid SearchCV**

In [57]:
from sklearn.model_selection import GridSearchCV

In [84]:
grid_search = GridSearchCV(SVC(),param_grid={
    'C':[1,10,20,50,100],
    'kernel':['linear','rbf','poly']
} ,scoring='accuracy',cv=5,return_train_score=False)

In [85]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 10, 20, 50, 100],
                         'kernel': ['linear', 'rbf', 'poly']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [86]:
df=pd.DataFrame(data=grid_search.cv_results_)

In [87]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1       linear         0.983333
1        1          rbf         0.950000
2        1         poly         0.950000
3       10       linear         0.958333
4       10          rbf         0.975000
5       10         poly         0.941667
6       20       linear         0.950000
7       20          rbf         0.966667
8       20         poly         0.950000
9       50       linear         0.941667
10      50          rbf         0.958333
11      50         poly         0.958333
12     100       linear         0.950000
13     100          rbf         0.941667
14     100         poly         0.958333

In [88]:
grid_search.best_estimator_

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [89]:
grid_search.best_params_

{'C': 1, 'kernel': 'linear'}

In [90]:
grid_search.best_score_

0.9833333333333334

**Using Random SearchCV**

In [91]:
from sklearn.model_selection import RandomizedSearchCV

In [92]:
random_search = RandomizedSearchCV(SVC(),param_distributions={
    'C':[1,10,20,50,100],
    'kernel':['linear','rbf','poly']
} ,scoring='accuracy',cv=5,return_train_score=False)

In [93]:
random_search.fit(X_train,y_train)

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                                 class_weight=None, coef0=0.0,
                                 decision_function_shape='ovr', degree=3,
                                 gamma='scale', kernel='rbf', max_iter=-1,
                                 probability=False, random_state=None,
                                 shrinking=True, tol=0.001, verbose=False),
                   iid='deprecated', n_iter=10, n_jobs=None,
                   param_distributions={'C': [1, 10, 20, 50, 100],
                                        'kernel': ['linear', 'rbf', 'poly']},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring='accuracy', verbose=0)

In [98]:
df=pd.DataFrame(data=random_search.cv_results_)
df

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.002555      0.000894  ...        0.000000                4
1       0.001752      0.000130  ...        0.000000                4
2       0.001578      0.000039  ...        0.031180                3
3       0.001581      0.000065  ...        0.026352                4
4       0.001564      0.000165  ...        0.016667                7
5       0.001670      0.000105  ...        0.016667                7
6       0.001658      0.000078  ...        0.020412                2
7       0.001465      0.000015  ...        0.016667                7
8       0.001530      0.000035  ...        0.020412               10
9       0.001656      0.000132  ...        0.020412                1

[10 rows x 15 columns]

In [100]:
df[['param_kernel','param_C','mean_test_score']]

param_kernel param_C  mean_test_score
0         poly      50         0.958333
1         poly     100         0.958333
2          rbf      20         0.966667
3          rbf      50         0.958333
4       linear     100         0.950000
5          rbf       1         0.950000
6          rbf      10         0.975000
7       linear      20         0.950000
8         poly      10         0.941667
9       linear       1         0.983333

In [101]:
dir(random_search)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_check_is_fitted',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_required_parameters',
 '_run_search',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_iter',
 'n_jobs',
 'n_splits_',
 'param_distributions',
 'pre_dispatch',
 'predict',
 

In [102]:
random_search.best_params_

{'C': 1, 'kernel': 'linear'}

In [103]:
random_search.best_score_

0.9833333333333334