<a href="https://colab.research.google.com/github/sharinair14/Basic-ML-Practice/blob/master/GridsearchCV_Example_iris_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

In [73]:
iris=load_iris()

In [74]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [75]:
iris.data[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [76]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [77]:
iris.target[:3]

array([0, 0, 0])

In [78]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [79]:
df=pd.DataFrame(data=iris.data,columns=iris.feature_names)

In [80]:
df['target'] = iris.target

In [81]:
X = df.drop('target',axis=1)

In [82]:
y = df['target']

In [18]:
from sklearn.model_selection import train_test_split

In [83]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [25]:
from sklearn.svm import SVC


**Without Grid Search**

In [23]:
svm = SVC()

In [24]:
svm.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
svm.score(X_test,y_test)

0.9666666666666667

In [27]:
from sklearn.model_selection import cross_val_score

In [29]:
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),X_train,y_train,scoring='accuracy',cv=5)

array([0.95833333, 1.        , 1.        , 1.        , 0.83333333])

In [30]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),X_train,y_train,scoring='accuracy',cv=5)

array([0.91666667, 1.        , 1.        , 1.        , 0.83333333])

In [31]:
cross_val_score(SVC(kernel='linear',C=20,gamma='auto'),X_train,y_train,scoring='accuracy',cv=5)

array([0.95833333, 1.        , 1.        , 1.        , 0.83333333])

**One more mothod without using Grid SearchCV**

In [56]:
kernel=['linear','rbf']
c = [1,10,20,50,100]
scores = {}
for i in kernel:
  for j in c:
    crossval_score = cross_val_score(SVC(kernel=i,C=j,gamma='auto'),X_train,y_train,cv=5,scoring='accuracy')
    scores[i + '_' + str(j)] = np.average(crossval_score)*100
scores

{'linear_1': 95.0,
 'linear_10': 91.66666666666666,
 'linear_100': 91.66666666666666,
 'linear_20': 90.0,
 'linear_50': 90.83333333333334,
 'rbf_1': 95.0,
 'rbf_10': 91.66666666666666,
 'rbf_100': 90.0,
 'rbf_20': 90.0,
 'rbf_50': 90.83333333333334}

**Using Grid SearchCV**

In [57]:
from sklearn.model_selection import GridSearchCV

In [84]:
grid_search = GridSearchCV(SVC(),param_grid={
    'C':[1,10,20,50,100],
    'kernel':['linear','rbf','poly']
} ,scoring='accuracy',cv=5,return_train_score=False)

In [85]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 10, 20, 50, 100],
                         'kernel': ['linear', 'rbf', 'poly']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [86]:
df=pd.DataFrame(data=grid_search.cv_results_)

In [87]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1       linear         0.983333
1        1          rbf         0.950000
2        1         poly         0.950000
3       10       linear         0.958333
4       10          rbf         0.975000
5       10         poly         0.941667
6       20       linear         0.950000
7       20          rbf         0.966667
8       20         poly         0.950000
9       50       linear         0.941667
10      50          rbf         0.958333
11      50         poly         0.958333
12     100       linear         0.950000
13     100          rbf         0.941667
14     100         poly         0.958333

In [88]:
grid_search.best_estimator_

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [89]:
grid_search.best_params_

{'C': 1, 'kernel': 'linear'}

In [90]:
grid_search.best_score_

0.9833333333333334