<a href="https://colab.research.google.com/github/sharinair14/Python-programs/blob/master/Spam_Dataset_using_Naive_Bayes_For_Basic_Understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [126]:
import numpy as np
import pandas as pd

In [162]:
data = pd.read_csv('/content/spam.csv',encoding='latin-1')

In [163]:
data.head()

v1  ... Unnamed: 4
0   ham  ...        NaN
1   ham  ...        NaN
2  spam  ...        NaN
3   ham  ...        NaN
4   ham  ...        NaN

[5 rows x 5 columns]

In [164]:
df=pd.DataFrame(data)

In [165]:
df=df.rename(columns={'v1':'Category','v2':'Message'})

In [166]:
df.head()

Category  ... Unnamed: 4
0      ham  ...        NaN
1      ham  ...        NaN
2     spam  ...        NaN
3      ham  ...        NaN
4      ham  ...        NaN

[5 rows x 5 columns]

In [167]:
df=df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)

In [168]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [169]:
df.groupby(df['Category']).describe()

Message                                                               
           count unique                                                top freq
Category                                                                       
ham         4825   4516                             Sorry, I'll call later   30
spam         747    653  Please call our customer service representativ...    4

In [170]:
df['Spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [171]:
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [172]:
from sklearn.model_selection import train_test_split

In [173]:
X_train,X_test,y_train,y_test = train_test_split(df['Message'],df['Spam'],test_size=0.2)

In [174]:
X_train.head()

4980                               I said its okay. Sorry
5481                      Shall call now dear having food
705     I don't think I can get away for a trek that l...
4664                  Ok set let u noe e details later...
1032                           HAPPY NEW YEAR MY NO.1 MAN
Name: Message, dtype: object

In [175]:
y_train.head()

4980    0
5481    0
705     0
4664    0
1032    0
Name: Spam, dtype: int64

In [141]:
from sklearn.feature_extraction.text import CountVectorizer

In [142]:
c=CountVectorizer()

In [143]:
X_train_new=c.fit_transform(X_train.values)

In [148]:
type(X_train_new)

scipy.sparse.csr.csr_matrix

In [149]:
X_train_new.toarray()[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [150]:
from sklearn.naive_bayes import MultinomialNB

In [151]:
nb=MultinomialNB()

In [152]:
nb.fit(X_train_new,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [153]:
email=["WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.",
       "I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.",
       'XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL']

In [154]:
email_new=c.transform(email)

In [155]:
nb.predict(email_new)

array([1, 0, 1])

Another method using Pipeline

In [176]:
from sklearn.pipeline import Pipeline

In [179]:
clf = Pipeline([
                ('vectoriser',CountVectorizer()),
                ('nb',MultinomialNB())
                ])

In [180]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vectoriser',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [181]:
clf.predict(X_test)

array([0, 0, 1, ..., 0, 0, 1])

In [182]:
clf.predict(email)

array([1, 0, 1])