<a href="https://colab.research.google.com/github/sharinair14/Python-programs/blob/master/Titanic_Dataset_using_Naive_Bayes_For_Basic_Understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


In [2]:
data = sns.load_dataset('titanic')

In [3]:
data.head()

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [37]:
df = pd.DataFrame(data,columns=['pclass','sex','age','sibsp','parch','fare','embarked'])

In [38]:
df.head()

pclass     sex   age  sibsp  parch     fare embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [39]:
col=['sex','embarked']


In [40]:
df_dummy=pd.get_dummies(df,prefix=col,prefix_sep='-',drop_first=False)

In [41]:
df_dummy.head()

pclass   age  sibsp  parch  ...  sex-male  embarked-C  embarked-Q  embarked-S
0       3  22.0      1      0  ...         1           0           0           1
1       1  38.0      1      0  ...         0           1           0           0
2       3  26.0      0      0  ...         0           0           0           1
3       1  35.0      1      0  ...         0           0           0           1
4       3  35.0      0      0  ...         1           0           0           1

[5 rows x 10 columns]

In [42]:
df_dummy.isna().sum()

pclass          0
age           177
sibsp           0
parch           0
fare            0
sex-female      0
sex-male        0
embarked-C      0
embarked-Q      0
embarked-S      0
dtype: int64

In [43]:
df_dummy['age'].head(20)

0     22.0
1     38.0
2     26.0
3     35.0
4     35.0
5      NaN
6     54.0
7      2.0
8     27.0
9     14.0
10     4.0
11    58.0
12    20.0
13    39.0
14    14.0
15    55.0
16     2.0
17     NaN
18    31.0
19     NaN
Name: age, dtype: float64

In [44]:
mean_age = np.mean(df_dummy['age'])

In [45]:
mean_age

29.69911764705882

In [46]:
df_dummy['age']=df_dummy['age'].fillna(mean_age)

In [47]:
df_dummy.isna().sum()

pclass        0
age           0
sibsp         0
parch         0
fare          0
sex-female    0
sex-male      0
embarked-C    0
embarked-Q    0
embarked-S    0
dtype: int64

In [48]:
target = data['survived']

In [49]:
target[:10]

0    0
1    1
2    1
3    1
4    0
5    0
6    0
7    0
8    1
9    1
Name: survived, dtype: int64

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train,X_test,y_train,y_test = train_test_split(df_dummy,target,test_size=0.2)

In [52]:
len(X_train)

712

In [53]:
len(X_test)

179

In [54]:
len(df_dummy)

891

In [55]:
len(y_test)

179

In [56]:
from sklearn.naive_bayes import GaussianNB

In [57]:
nb = GaussianNB()

In [58]:
nb.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [59]:
nb.score(X_test,y_test)

0.8044692737430168

In [60]:
X_test[:10]

pclass        age  sibsp  ...  embarked-C  embarked-Q  embarked-S
453       1  49.000000      1  ...           1           0           0
201       3  29.699118      8  ...           0           0           1
543       2  32.000000      1  ...           0           0           1
702       3  18.000000      0  ...           1           0           0
27        1  19.000000      3  ...           0           0           1
529       2  23.000000      2  ...           0           0           1
808       2  39.000000      0  ...           0           0           1
863       3  29.699118      8  ...           0           0           1
809       1  33.000000      1  ...           0           0           1
426       2  28.000000      1  ...           0           0           1

[10 rows x 10 columns]

In [61]:
ypred = nb.predict(X_test)

In [62]:
ypred[:10]

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1])

In [63]:
prob = nb.predict_proba(X_test)

In [64]:
prob[:10]

array([[3.12322472e-02, 9.68767753e-01],
       [1.00000000e+00, 6.54781099e-18],
       [9.85723465e-01, 1.42765354e-02],
       [5.83023056e-03, 9.94169769e-01],
       [5.55185072e-13, 1.00000000e+00],
       [9.95253322e-01, 4.74667815e-03],
       [9.85946393e-01, 1.40536075e-02],
       [1.00000000e+00, 5.61866152e-15],
       [9.03679695e-03, 9.90963203e-01],
       [7.20432990e-02, 9.27956701e-01]])

In [65]:
np.round(prob[:10],3)

array([[0.031, 0.969],
       [1.   , 0.   ],
       [0.986, 0.014],
       [0.006, 0.994],
       [0.   , 1.   ],
       [0.995, 0.005],
       [0.986, 0.014],
       [1.   , 0.   ],
       [0.009, 0.991],
       [0.072, 0.928]])

In [33]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [66]:
print('Accuracy is ',accuracy_score(y_test,ypred))

Accuracy is  0.8044692737430168


In [67]:
print('Confusion Matrix',confusion_matrix(y_test,ypred))

Confusion Matrix [[89 17]
 [18 55]]


In [68]:
print('Classification Report',classification_report(y_test,ypred))

Classification Report               precision    recall  f1-score   support

           0       0.83      0.84      0.84       106
           1       0.76      0.75      0.76        73

    accuracy                           0.80       179
   macro avg       0.80      0.80      0.80       179
weighted avg       0.80      0.80      0.80       179

